version: "3.9"

services:
  db:
    image: postgres:16
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  web:
    build: ./web
    container_name: library_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://app_user:app_password@db:5432/library
    depends_on:
      - db

